Repository at-luantran/inter-summer, pull requests merged in 2018-08, with the labels that each got.

#20 Product Detail Public
  Gemfile
  Gemfile.lock
  app/assets/images/loading.gif
  app/assets/javascripts/application.js
  app/assets/javascripts/products.js
  app/assets/stylesheets/products.scss
  app/controllers/products_controller.rb
  app/helpers/products_helper.rb
  app/views/products/show.html.erb
  config/routes.rb
  test/controllers/products_controller_test.rb
Labels: Merged, New feature

#22 Manage timer aution
  app/controllers/admin/products_controller.rb
  app/controllers/admin/timers_controller.rb
  app/helpers/admin/timers_helper.rb
  app/models/auction.rb
  app/models/product.rb
  app/models/timer.rb
  app/validators/after_validator.rb
  app/views/admin/products/_product.html.erb
  app/views/admin/timers/_form.html.erb
  app/views/admin/timers/edit.html.erb
  app/views/admin/timers/new.html.erb
  config/routes.rb
  db/migrate/20180809042550_create_timers.rb
  db/migrate/20180809042614_create_auctions.rb
  db/schema.rb
  test/controllers/admin/timers_controller_test.rb
  test/fixtures/timers.yml
  test/models/timer_test.rb
Labels: Merged, New feature

#24 Template Cart
  app/assets/images/delete1.png
  app/assets/images/delivery-car.png
  app/assets/images/money.png
  app/assets/images/my_bank.png
  app/assets/stylesheets/orders.scss
  app/assets/stylesheets/products.scss
  app/controllers/admin/auctions_controller.rb
  app/controllers/admin/products_controller.rb
  app/controllers/application_controller.rb
  app/controllers/orders_controller.rb
  app/helpers/orders_helper.rb
  app/views/orders/_cart_table.html.erb
  app/views/orders/index.html.erb
  config/routes.rb
  test/controllers/orders_controller_test.rb
Labels: Merged, New feature

#23 Timer index edit delete
  app/controllers/admin/timers_controller.rb
  app/models/common/const.rb
  app/models/product.rb
  app/views/admin/products/_product.html.erb
  app/views/admin/timers/_form.html.erb
  app/views/admin/timers/_timer.html.erb
  app/views/admin/timers/edit.html.erb
  app/views/admin/timers/index.html.erb
  app/views/layouts/admin/application.html.erb
Labels: Merged, New feature

#25 Add validate image
  app/models/asset.rb
  app/views/admin/products/_asset_fields.html.erb
  config/locales/en.yml
Labels: Merged, Reviewing

#26 Show Cart And Delete Item
  app/assets/stylesheets/orders.scss
  app/controllers/admin/products_controller.rb
  app/controllers/orders_controller.rb
  app/views/items/_item.html.erb
  app/views/layouts/_header.html.erb
  app/views/orders/_cart_table.html.erb
  app/views/orders/index.html.erb
  config/routes.rb
  db/migrate/20180816102244_add_status_to_orders.rb
  db/schema.rb
Labels: New feature, Reviewing
